import { beforeEach, expect, it, vi } from "vitest";
const mock = vi.hoisted(() => ({ auth: vi.fn(), rpc: vi.fn() }));
vi.mock("../src/lib/auth",()=>({requireAdmin:mock.auth}));
vi.mock("../src/lib/db",()=>({database:()=>({rpc:mock.rpc}),dbError:(error:unknown)=>{if(error)throw Error("db");}}));
import { adminAssistantNotes } from "../src/lib/assistant-notes";
const note={id:"note",title:"กาแฟ",content:"ไม่หวาน",group:null,sourceLabel:"แชตส่วนตัวของฉัน",updated_at:"2026-10-10"};
beforeEach(()=>{vi.clearAllMocks();mock.auth.mockResolvedValue({id:"admin"});mock.rpc.mockResolvedValue({data:{notes:[note],events:[],deliveries:[]},error:null});});
it("requires admin before reading the batch",async()=>{mock.auth.mockRejectedValue(Error("denied"));await expect(adminAssistantNotes()).rejects.toThrow("denied");expect(mock.rpc).not.toHaveBeenCalled();});
it("reads the authorized notes in one RPC",async()=>{expect(await adminAssistantNotes()).toEqual([note]);expect(mock.rpc).toHaveBeenCalledExactlyOnceWith("pp_admin_notebooks");});
it("does not persist notebook data between separate calls",async()=>{await adminAssistantNotes();mock.rpc.mockResolvedValue({data:{notes:[],events:[],deliveries:[]},error:null});expect(await adminAssistantNotes()).toEqual([]);expect(mock.rpc).toHaveBeenCalledTimes(2);});
it("fails closed on database errors and malformed responses",async()=>{mock.rpc.mockResolvedValue({data:null,error:{code:"error"}});await expect(adminAssistantNotes()).rejects.toThrow("db");mock.rpc.mockResolvedValue({data:{},error:null});await expect(adminAssistantNotes()).rejects.toThrow("Invalid notebook snapshot");});
