import Link from "next/link";
export default function Home() {
  return <main className="landing">
    <header className="topbar"><Link className="brand" href="/"><span className="mark">pp<span>•</span></span><span>PP <small>YOUR PERSON, IN THE GROUP.</small></span></Link><Link className="button secondary" href="/admin">เข้าแอดมิน ↗</Link></header>
    <section className="hero"><div><div className="eyebrow">A LITTLE YOU. ALWAYS A FRIEND.</div><h1>ให้เพื่อนเรียก <em>@pp</em><br/>ที่เหลือ เราช่วยตอบเอง<span className="accent">.</span></h1><p className="intro">ตัวแทนเล็ก ๆ ของคุณในกลุ่ม LINE<br/>จำเฉพาะเรื่องที่คุณอยากเล่า รู้ว่าเมื่อไหร่ควรเรียกคุณ</p><div className="row"><Link className="button" href="/admin">จัดการความจำ <span>↗</span></Link><span className="muted">PP / VERSION 0.1</span></div><div className="pills"><span>เรียกแล้วค่อยตอบ</span><span>ความลับอยู่กับคุณ</span><span>ไม่รู้ก็ไม่เดา</span></div></div>
    <div className="chat-card"><div className="chat-heading"><span className="avatar">☺</span><div><strong>แก๊งเพื่อนสนิท</strong><small>ตัวอย่างบทสนทนา · PP อยู่ในกลุ่มแล้ว</small></div><span className="dots">•••</span></div><div className="chat-body"><div className="chat-label">เม้ง</div><div className="bubble friend"><b>@pp</b> ปีโป้ชอบกินอะไร</div><div className="chat-label bot-label">PP <span>BOT</span></div><div className="bubble bot">ชอบอาหารไทยเป็นหลักเลย 😄</div><div className="chat-label">กร</div><div className="bubble friend"><b>@pp</b> ปีโป้เสาร์นี้ว่างไหม</div><div className="chat-label bot-label">PP <span>BOT</span></div><div className="bubble bot">อันนี้ให้เจ้าตัวตอบดีกว่า 😄<br/><b>@ปีโป้</b> มาช่วยตอบเพื่อนหน่อย</div><p className="chat-note">ตัวอย่างสมมติ · คำตอบจริงมาจากความจำที่คุณเพิ่ม</p></div></div></section>
    <section className="principles"><article><span>01 / MEMORY</span><h2>จำเท่าที่คุณอนุญาต</h2><p>เพิ่มคำถามกับคำตอบ แล้วเลือกว่าจะให้เพื่อนรู้ หรือเก็บไว้ส่วนตัว</p></article><article><span>02 / BOUNDARIES</span><h2>มีขอบเขตเหมือนเพื่อน</h2><p>เรื่องส่วนตัวขอผ่าน เรื่องที่ยังไม่รู้จะไม่แต่งขึ้นมาเอง</p></article><article><span>03 / HANDOFF</span><h2>ถึงตาคุณเมื่อจำเป็น</h2><p>เมื่อเพื่อนชวนนัดและ PP ไม่รู้คำตอบ จะเรียกคุณด้วยแท็ก LINE จริง</p></article></section>
    <footer><span>PP — ตัวแทนของคุณ ไม่ใช่ตัวคุณ</span><Link href="/setup">คู่มือเริ่มต้น ↗</Link></footer>
  </main>;
}
