import Link from "next/link";
import { requireAdmin } from "@/lib/auth";
import { database, dbError } from "@/lib/db";
import { MemoryForm, DeleteMemory, OwnerForm, PermissionForm, type Memory, type Permission } from "@/components/admin-forms";
import { logout } from "@/app/login/actions";
import { saveFriend } from "./actions";
export const dynamic = "force-dynamic";
const labels: Record<string,string> = { answer: "ตอบจากความจำ", refuse: "ขอไม่ตอบ", unknown: "ยังไม่รู้", handoff: "ให้เจ้าตัวตอบ", rate_limit: "พักการตอบ", delivery_error: "ส่งไม่สำเร็จ" };
export default async function Admin() {
  await requireAdmin();
  const db = database();
  const [owner, memories, permissions, friends, conversations] = await Promise.all([
    db.from("owner").select("display_name,line_user_id").eq("id", 1).single(),
    db.from("memories").select("id,title,content,visibility,question_examples,expires_at").order("updated_at", { ascending: false }).limit(200),
    db.from("permissions").select("group_id,label,enabled,allow_owner_mention").order("created_at", { ascending: false }).limit(100),
    db.from("friends").select("id,group_id,line_user_id,display_name,blocked").order("created_at", { ascending: false }).limit(100),
    db.from("conversations").select("event_id,group_id,status,decision,created_at").order("created_at", { ascending: false }).limit(30)
  ]);
  for (const result of [owner, memories, permissions, friends, conversations]) dbError(result.error);
  const items = (memories.data || []) as Memory[];
  const groups = (permissions.data || []) as Permission[];
  return <div className="admin-shell"><aside className="sidebar"><Link className="brand" href="/"><span className="mark">pp<span>•</span></span><span>PP <small>YOUR SPACE</small></span></Link><nav><a href="#memories">◈ ความจำ</a><a href="#owner">☺ เจ้าของ</a><a href="#groups">▦ กลุ่มและสิทธิ์</a><a href="#friends">♡ เพื่อน</a><a href="#activity">↗ การตอบล่าสุด</a></nav><div className="sidebar-bottom"><span className="status-dot"/> เจ้าของเป็นคนเลือกสิ่งที่ PP รู้<form action={logout}><button className="secondary">ออกจากระบบ</button></form></div></aside><main className="dashboard"><header className="dashboard-heading"><div><div className="eyebrow">A LITTLE MEMORY GOES A LONG WAY</div><h1>สวัสดี, {owner.data?.display_name}<span className="accent">.</span></h1><p>วันนี้อยากให้ PP ช่วยเล่าเรื่องอะไรให้เพื่อนฟัง?</p></div><a className="button" href="#new-memory">เพิ่มความจำ +</a></header><div className="stats"><article><span>ความจำทั้งหมดที่แสดง</span><strong>{items.length}</strong></article><article><span>แบ่งปันกับเพื่อนได้</span><strong>{items.filter(m => m.visibility === "shareable").length}</strong></article><article><span>เก็บไว้ส่วนตัว</span><strong>{items.filter(m => m.visibility === "private").length}</strong></article><article><span>กลุ่มที่เปิดใช้งาน</span><strong>{groups.filter(g => g.enabled).length}</strong></article></div><div className="notice">PP ตอบเมื่อคำถามตรงกับตัวอย่างที่คุณเพิ่มไว้ โดยข้ามช่องว่างและเครื่องหมายคำถาม หากมีหลายคำตอบที่ขัดกันจะขอไม่ตอบ</div>
    <section id="memories"><div className="section-heading"><h2>ความจำของ PP</h2><span className="muted">แสดงล่าสุดสูงสุด 200 รายการ</span></div><div className="memory-grid"><article className="panel new-memory" id="new-memory"><div className="eyebrow">NEW MEMORY</div><h3>เรื่องที่อยากให้จำ</h3><MemoryForm/></article><div className="stack">{items.length === 0 ? <div className="empty"><div>✳</div><h3>เริ่มจากเรื่องเล็ก ๆ ก็ได้</h3><p>อาหารที่ชอบ เกมที่เล่น หรือคำถามที่เพื่อนถามบ่อย<br/>เลือก Shareable เมื่อพร้อมให้ทั้งกลุ่มรู้</p></div> : items.map(memory => <article className="panel" key={memory.id}><div className="row between"><h3>{memory.title}</h3><span className={`badge ${memory.visibility}`}>{memory.visibility === "private" ? "◈ Private" : "↗ Shareable"}</span></div><p className="memory-content">{memory.content}</p><details><summary>แก้ไขความจำ</summary><MemoryForm memory={memory}/><DeleteMemory id={memory.id}/></details></article>)}</div></div></section>
    <div className="settings-grid"><section id="owner" className="panel"><div className="eyebrow">THE HUMAN BEHIND PP</div><h2>เจ้าของ PP</h2><OwnerForm owner={owner.data || { display_name: "ปีโป้", line_user_id: null }}/></section><section id="groups" className="panel"><div className="eyebrow">CLOSE FRIENDS ONLY</div><h2>กลุ่มและสิทธิ์</h2><p>แท็ก PP จริงในกลุ่มหนึ่งครั้ง กลุ่มจะปรากฏที่นี่และรอคุณอนุมัติ</p>{groups.map(group => <details key={group.group_id}><summary>{group.enabled ? "🟢" : "⚪"} {group.label || group.group_id}</summary><PermissionForm permission={group}/></details>)}<details><summary>เพิ่มกลุ่มด้วย ID</summary><PermissionForm/></details></section></div>
    <section id="friends" className="panel"><h2>เพื่อนในกลุ่ม</h2><p>เพื่อนจะปรากฏเมื่อเรียก PP ในกลุ่มที่อนุมัติแล้ว · แสดงล่าสุดสูงสุด 100 คน</p>{friends.data?.length ? friends.data.map(friend => <form action={saveFriend} className="friend-row" key={friend.id}><input type="hidden" name="id" value={friend.id}/><div><code>{friend.line_user_id}</code><small>{groups.find(g => g.group_id === friend.group_id)?.label || friend.group_id}</small></div><label>ชื่อเพื่อน<input name="display_name" defaultValue={friend.display_name} maxLength={80}/></label><label className="check"><input name="blocked" type="checkbox" defaultChecked={friend.blocked}/>พักการตอบคนนี้</label><button className="secondary">บันทึก</button></form>) : <p className="muted">ยังไม่มีเพื่อนเรียก PP</p>}</section>
    <section id="activity" className="panel"><h2>การตอบล่าสุด</h2><p>เก็บเฉพาะสถานะและ ID ที่จำเป็น 30 วัน ไม่มีข้อความสนทนาดิบหรือเนื้อหา private</p><div className="table-wrap"><table><thead><tr><th>เวลา</th><th>กลุ่ม</th><th>การตัดสินใจ</th><th>การส่ง</th></tr></thead><tbody>{conversations.data?.map(item => <tr key={item.event_id}><td>{new Intl.DateTimeFormat("th-TH", { timeZone: "Asia/Bangkok", dateStyle: "short", timeStyle: "short" }).format(new Date(item.created_at))}</td><td>{groups.find(g => g.group_id === item.group_id)?.label || item.group_id}</td><td>{labels[item.decision || ""] || "กำลังประมวลผล"}</td><td>{item.status}</td></tr>)}</tbody></table></div>{!conversations.data?.length && <p className="muted">พร้อมเมื่อเพื่อนเรียก @pp</p>}</section></main></div>;
}
